local variable = require("main/modules/variable") -- import variables

function init(self)
    msg.post(".", "acquire_input_focus")
    self.turnRate = 0.4 -- 0.4
end

function on_input(self, action_id, action)
    if action_id == hash("a") then -- left
        variable.modifybAngle(variable.bAngle + self.turnRate)
        if variable.bAngle > 180 then -- keep boat within range
            variable.modifybAngle(variable.bAngle - 360)
        end
        go.set_rotation(vmath.quat_rotation_z(math.rad(variable.bAngle))) -- rotate boat

    elseif action_id == hash("d") then  -- right
        variable.modifybAngle(variable.bAngle - self.turnRate)
        if variable.bAngle < -180 then
            variable.modifybAngle(variable.bAngle + 360)
        end
        go.set_rotation(vmath.quat_rotation_z(math.rad(variable.bAngle)))
    end
end

--